version: "3.9"
services:
  app:
    build:
      target: runtime
      context: api
      args:
        - DATABASE_URL=mysql://user:password@db:3306/suzuki
    tty: true
    ports:
      - 18080:8080
    stop_signal: SIGHUP
    volumes:
      - ./api:/app/
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
    depends_on:
      - db

  app_dev:
    build:
      target: builder
      context: api
      args:
        - DATABASE_URL=mysql://user:password@db:3306/suzuki
    tty: true
    ports:
      - 18080:8080
    stop_signal: SIGHUP
    volumes:
      - ./api:/app/
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
    depends_on:
      - db
    profiles:
      - dev
  db:
    image: mysql:8.0.27
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: suzuki
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      # TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    links:
      - db
    ports:
      - 40:80
    volumes:
      - pma_session:/sessions
    profiles:
      - dev

volumes:
  cargo_cache:
  mysql-data:
  pma_session:
  target_cache:


